<a href="https://colab.research.google.com/github/nandanajayachandran/NANDANA_J_ICT_ASSIGNMENTS_CASE_STUDIES/blob/main/Nandana_J_Coding_Exit_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CODING TEST - Sentiment Analysis on Movie Reviews**

In [49]:
#Importing necessary libraries
import pandas as pd
import numpy as np

In [50]:
#Reading the dataset into python environment
data = pd.read_csv('/content/labeledTrainData.tsv', sep='\t')
data

id  sentiment                                             review
0       5814_8          1  With all this stuff going down at the moment w...
1       2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2       7759_3          0  The film starts with a manager (Nicholas Bell)...
3       3630_4          0  It must be assumed that those who praised this...
4       9495_8          1  Superbly trashy and wondrously unpretentious 8...
...        ...        ...                                                ...
24995   3453_3          0  It seems like more consideration has gone into...
24996   5064_1          0  I don't believe they made this film. Completel...
24997  10905_3          0  Guy is a loser. Can't get girls, needs to buil...
24998  10194_3          0  This 30 minute documentary Buñuel made in the ...
24999   8478_8          1  I saw this movie as a child and it broke my he...

[25000 rows x 3 columns]

In [51]:
data.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

**DATA PREPROCESSING**

In [52]:
#Handling missing values if present
data.dropna(inplace=True)

In [53]:
#Removing punctuations, URLs, tags, RTs, and repeated characters from the text
def remove_pun(text):
    #Remove punctuation
    text = ''.join([i for i in text if i not in string.punctuation])
    #Removing URL
    text = re.sub(r'http\S+|www\S+|\S+\.com\S+', '', text, flags=re.MULTILINE)
    #Removing the tags from the text
    text = re.sub(r'(@\S+) | (#\S+)', r'', text)
    #Removing the RT from the text
    text = re.sub(r'\bRT\b', r'', text)
    #Removing repeated characters
    text = re.sub(r'(.)\1+', r'\1', text)
    return text

In [54]:
#Tokenize the given text into words
import nltk
nltk.download('punkt')
def tokenize(text):
    words = nltk.word_tokenize(text)
    return words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [55]:
#Remove stopwords from the given text
def remove_stopwords(words):
    stop_words = set(stopwords.words('english'))
    output = [word for word in words if word.lower() not in stop_words]
    return output

In [56]:
# #Remove stopwords from the given text
# nltk.download('stopwords')
# stopwords = nltk.corpus.stopwords.words('english')
# def remove_stopwords(text):
#     output = [i for i in text if i not in stopwords]
#     return output

In [57]:
#Lemmatization
wordnet_lemm = WordNetLemmatizer()
def lemma(words):
    lemmatized_words = [wordnet_lemm.lemmatize(word) for word in words]
    return lemmatized_words

In [58]:
data.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [59]:
def preprocess(data_col):
  corpus = []
  for item in data_col:
    new_item = remove_pun(item)
    new_item = new_item.lower()
    new_item = tokenize(new_item)
    new_item = remove_stopwords(new_item)
    new_item = lemma(new_item)
    corpus.append(' '.join(str(x) for x in new_item))
  return corpus

In [60]:
import string
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [61]:
corpus = preprocess(data['review'])

**Splitting the dataset**

In [63]:
from sklearn.model_selection import train_test_split

In [65]:
x_train, x_test, y_train, y_test = train_test_split(corpus, data['sentiment'], test_size=0.2, random_state=42)

# **FEATURE EXTRACTION**

**BAG OF WORDS**

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1, 2))

#Fitting and transforming the training data
train_vectors = cv.fit_transform(x_train)

#Transforming the test data
test_vectors = cv.transform(x_test)

#Assign the feature matrix and labels
x = train_vectors
y = y_train


**MODEL BULDING & EVALUATION**

**NAIVE BAYES MODEL**

In [68]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [69]:
#Training the Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(train_vectors, y_train)

#Making predictions on the test set
predictions = classifier.predict(test_vectors)

In [72]:
#Accuracy of the model
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 87.88%


In [73]:
#Printing the classification report
print('\nClassification Report:')
print(classification_report(y_test, predictions))

#Printing the confusion matrix
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, predictions))


Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.89      0.88      2481
           1       0.89      0.87      0.88      2519

    accuracy                           0.88      5000
   macro avg       0.88      0.88      0.88      5000
weighted avg       0.88      0.88      0.88      5000


Confusion Matrix:
[[2201  280]
 [ 326 2193]]


**LOGISTIC REGRESSION**

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [77]:
#Training the Logistic Regression model
logistic_classifier = LogisticRegression()
logistic_classifier.fit(train_vectors, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [76]:
#Making predictions on the test set
logistic_predictions = logistic_classifier.predict(test_vectors)

In [79]:
#Accuracy of the model
logistic_accuracy = accuracy_score(y_test, logistic_predictions)
print(f'Logistic Regression Accuracy: {logistic_accuracy * 100:.2f}%')

Logistic Regression Accuracy: 88.70%


In [78]:
#printing the classification report
print('Classification Report:\n', classification_report(y_test, logistic_predictions))

#printing the confusion matrix
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, logistic_predictions))

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.87      0.88      2481
           1       0.88      0.90      0.89      2519

    accuracy                           0.89      5000
   macro avg       0.89      0.89      0.89      5000
weighted avg       0.89      0.89      0.89      5000


Confusion Matrix:
[[2170  311]
 [ 254 2265]]


**RANDOM FOREST MODEL**

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [81]:
#Training the Random Forest model
rf_classifier = RandomForestClassifier()
rf_classifier.fit(train_vectors, y_train)

RandomForestClassifier()

In [82]:
#Making predictions on the test set
rf_predictions = rf_classifier.predict(test_vectors)

#Accuracy of the Random Forest model
rf_accuracy = accuracy_score(y_test, rf_predictions)
print(f'Random Forest Accuracy: {rf_accuracy * 100:.2f}%')

Random Forest Accuracy: 85.40%


In [83]:
#Printing the classification report
print('Classification Report:\n', classification_report(y_test, rf_predictions))

#Printing the confusion matrix
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, rf_predictions))

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.84      0.85      2481
           1       0.84      0.87      0.86      2519

    accuracy                           0.85      5000
   macro avg       0.85      0.85      0.85      5000
weighted avg       0.85      0.85      0.85      5000


Confusion Matrix:
[[2076  405]
 [ 325 2194]]


**SUPPORT VECTOR MACHINE MODEL**

In [84]:
from sklearn.svm import SVC

In [85]:
#Training the Support Vector Machine model
svm_classifier = SVC()
svm_classifier.fit(train_vectors, y_train)

SVC()

In [86]:
#Making predictions on the test set
svm_predictions = svm_classifier.predict(test_vectors)

#Accuracy of the SVM model
svm_accuracy = accuracy_score(y_test, svm_predictions)
print(f'SVM Accuracy: {svm_accuracy * 100:.2f}%')

SVM Accuracy: 87.50%


In [87]:
#Printing the classification report
print('Classification Report:\n', classification_report(y_test, svm_predictions))

#Printing the confusion matrix
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, svm_predictions))


Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.86      0.87      2481
           1       0.86      0.89      0.88      2519

    accuracy                           0.88      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.88      0.87      5000


Confusion Matrix:
[[2129  352]
 [ 273 2246]]


**XGBOOST CLASSIFIER**

In [88]:
from xgboost import XGBClassifier

In [89]:
#Training the XGBoost model
xgb_classifier = XGBClassifier()
xgb_classifier.fit(train_vectors, y_train)
#Making predictions on the test set
xgb_predictions = xgb_classifier.predict(test_vectors)

In [90]:
#Accuracy of the XGBoost model
xgb_accuracy = accuracy_score(y_test, xgb_predictions)
print(f'XGBoost Accuracy: {xgb_accuracy * 100:.2f}%')

XGBoost Accuracy: 85.66%


In [91]:
#Printing the classification report
print('Classification Report:\n', classification_report(y_test, xgb_predictions))

#Printing the confusion matrix
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, xgb_predictions))

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.83      0.85      2481
           1       0.84      0.88      0.86      2519

    accuracy                           0.86      5000
   macro avg       0.86      0.86      0.86      5000
weighted avg       0.86      0.86      0.86      5000


Confusion Matrix:
[[2058  423]
 [ 294 2225]]


On conducting thorough evaluations of different sentiment analysis models, including Naive Bayes, Logistic Regression,Random forest, Support Vector Machine and XGBoost. The **Logistic Regression model** is giving better accuracy in sentiment prediction on our dataset. Therefore, I have decided to **deploy the Logistic Regression model for sentiment analysis**.



In [111]:
#Defining the function to find sentiment using Logistic Regression
def find_sentiment_lr(input_text, logistic_classifier, cv):
    #Tokenize, remove stopwords, and lemmatize
    preprocessed_input = preprocess([input_text])[0]

    #Transform and predict sentiment
    prediction = logistic_classifier.predict(cv.transform([preprocessed_input]))[0]

    #Print the sentiment
    print('Positive sentiment' if prediction == 1 else 'Negative sentiment')

#Example usage for Logistic Regression model
find_sentiment_lr("I absolutely loved this movie! The acting was superb.", logistic_classifier, cv)
find_sentiment_lr("The plot was confusing, and I didn't enjoy it at all.", logistic_classifier, cv)

Positive sentiment
Negative sentiment
